[api_keys]
openai = YOUR_OPENAI_API_KEY
elevenlabs = YOUR_ELEVENLABS_API_KEY

[ai]
# model can be gpt-4, gpt-4o, gpt-4o-mini, or a local model like phi-3
model = gpt-4o-mini

[object_recognition]
# model can be yolov8n.pt, yolov8s.pt, etc.
model = yolov8n.pt
